#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: US ATLAS SUPER

# Short bio or description (displayed in the header)
description: US ATLAS SUPER

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://atlas.web.cern.ch/Atlas/Collaboration/images/ATLAS-Logo-Ref-RGB-160px.png

# Used for sitemap.xml
url: https://usatlas.github.io/super

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/super"

# Use the yaml.defaults to set the layout and
# author page variables
defaults:
  -
    scope:
      path: ""
    values:
      author: "US ATLAS SUPER"
  -
    scope:
      path: "guides/howto"
      type: "pages"
    values:
      layout: "default"
      author: "US ATLAS Physics Support"
  -
    scope:
      path: "guides/faq"
      type: "pages"
    values:
      layout: "default"
      author: "US ATLAS Physics Support"
  -
    scope:
      path: "guides/past"
      type: "pages"
    values:
      layout: "default"
      author: "US ATLAS Physics Support"
permalink: /:title/

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - ci_scripts
  - Makefile
  - .htmlproofer
